<a href="https://colab.research.google.com/github/OmkarPatkar/Coursera-Programming-for-Everybody-Getting-Started-with-Python-/blob/master/PythonBasics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Programming for Everybody (Getting Started with Python)**

**ASSIGNMENT OF WEEK 3**

1.1 Write a program that uses a print statement to say 'hello world' as shown in 'Desired Output'.

In [1]:
print("hello world")

hello world


**ASSIGNMENT OF WEEK 4**

2.2 Write a program that uses input to prompt a user for their name and then welcomes them. Note that input will pop up a dialog box. Enter Sarah in the pop-up box when you are prompted so your output will match the desired output.

In [2]:
name = input("Enter your name: ")
print("Hello", name)

Enter your name: Sarah
Hello Sarah


2.3 Write a program to prompt the user for hours and rate per hour using input to compute gross pay. Use 35 hours and a rate of 2.75 per hour to test the program (the pay should be 96.25). You should use input to read a string and float() to convert the string to a number. Do not worry about error checking or bad user data.

In [3]:
hrs = input("Enter Hours:")
rph = input("Enter rate per hour:")
hrs = float(hrs)
rph = float(rph)
pay = print("Pay:", (hrs * rph))

Enter Hours:35
Enter rate per hour:2.75
Pay: 96.25


**ASSIGNMENT OF WEEK 5**

3.1 Write a program to prompt the user for hours and rate per hour using input to compute gross pay. Pay the hourly rate for the hours up to 40 and 1.5 times the hourly rate for all hours worked above 40 hours. Use 45 hours and a rate of 10.50 per hour to test the program (the pay should be 498.75). You should use input to read a string and float() to convert the string to a number. Do not worry about error checking the user input - assume the user types numbers properly.

In [4]:
h = float(input("Enter Hours:"))
r = float(input("Enter rate:"))

pay = h * r

if pay > 40:
    mul = h * r
    b = (h - 40.0) * (r * 0.5)
    op = mul + b
else:
    op = h * r
    
print(op)
    

Enter Hours:45
Enter rate:10.50
498.75


3.3 Write a program to prompt for a score between 0.0 and 1.0. If the score is out of range, print an error. If the score is between 0.0 and 1.0, print a grade using the following table:
Score Grade
>= 0.9 A
>= 0.8 B
>= 0.7 C
>= 0.6 D
< 0.6 F
If the user enters a value out of range, print a suitable error message and exit. For the test, enter a score of 0.85.

In [5]:
score = float(input("Enter Score: "))

if score >= 0.9:
    print("A")
elif score >= 0.8:
    print("B")
elif score >= 0.7:
    print("C")
elif score >= 0.6:
    print("D")
elif score < 0.6:
    print("F")
else:
    print("value out of range")
    quit()

Enter Score: 0.85
B


**ASSIGNMENT OF WEEK 6**

4.6 Write a program to prompt the user for hours and rate per hour using input to compute gross pay. Pay should be the normal rate for hours up to 40 and time-and-a-half for the hourly rate for all hours worked above 40 hours. Put the logic to do the computation of pay in a function called computepay() and use the function to do the computation. The function should return a value. Use 45 hours and a rate of 10.50 per hour to test the program (the pay should be 498.75). You should use input to read a string and float() to convert the string to a number. Do not worry about error checking the user input unless you want to - you can assume the user types numbers properly. Do not name your variable sum or use the sum() function.

In [6]:
def computepay(h,r):
    if h>40:
        rate = (r * 1.5) * (h - 40.0)
        return ((h - 5)*r) + rate

hrs = float(input("Enter Hours:"))
rt = float(input("Enter rate:"))

p = computepay(hrs,rt)

print('Pay',p)

Enter Hours:45
Enter rate:10.50
Pay 498.75


**ASSIGNMENT OF WEEK 7**

5.2 Write a program that repeatedly prompts a user for integer numbers until the user enters 'done'. Once 'done' is entered, print out the largest and smallest of the numbers. If the user enters anything other than a valid number catch it with a try/except and put out an appropriate message and ignore the number. Enter 7, 2, bob, 10, and 4 and match the output below.

In [7]:
largest = None
smallest = None
the_list = []

while True:
    num = input("Enter a number: ")
    if num == "done" : break
    if len(num) < 1: break
    try:
      num = int(num)
      the_list.append(num)
    except:
      print('Invalid input')

smallest = min(the_list)
largest = max(the_list)
 
print("Maximum is", largest)
print("Minimum is", smallest)

Enter a number: 7
Enter a number: 2
Enter a number: bob
Invalid input
Enter a number: 10
Enter a number: 4
Enter a number: done
Maximum is 10
Minimum is 2
